//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeopleBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public int PeopleId { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Panronymic { get; set; }
        public string PassportData { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> Status_Id { get; set; }
        public Nullable<int> City_Id { get; set; }
        public string Street { get; set; }
        public string Building { get; set; }
        public string flat { get; set; }
        public string Photo { get; set; }
    
        public virtual City City { get; set; }
        public virtual Status Status { get; set; }
    }
}
